name: ref-tag
on: [push]
  # push:
  #   tags:
  #     - mono-code-prod-*

jobs:
  miyazaki-infra-staging-deployment:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Check the cntext
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Check the ref
        run: export APP_TAG=`printf $(git show-ref --abbrev=7 $GITHUB_REF)`
        env:
          GITHUB_REF: "refs/tags/mono-code-prod-6310e46"

      - name: Check the ref again
        run: echo $APP_TAG
      
      # - name: Get the ref
      # #   run: export APP_TAG="${$(echo $(git show-ref --abbrev=7 $REF)):0:7}" && docker pull docker.pkg.github.com/syukur91/mono-repo/hello-github:$APP_TAG
      #   run: export TAG=`echo $APP_TAG | cut -c1-7`
      
      - name: Print the tag
      #   run: export APP_TAG="${$(echo $(git show-ref --abbrev=7 $REF)):0:7}" && docker pull docker.pkg.github.com/syukur91/mono-repo/hello-github:$APP_TAG
        run: docker pull docker.pkg.github.com/syukur91/mono-repo/hello-github:$APP_TAG
        