name: ref-tag
on:
  push:
    tags:
      - mono-code-prod-*

jobs:
  miyazaki-infra-staging-deployment:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Check the cntext
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Get the ref
        run: export APP_TAG=`echo $(git show-ref --abbrev=7 $REF)` && echo "$APP_TAG"
        env:
          REF: ${{ toJson(github.ref) }}