name: ref-tag
on: 
  push:
    tags:
      - mono-code-prod-*

jobs:
  miyazaki-infra-staging-deployment:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Check the cntext
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: login to our private repository
        run: docker login docker.pkg.github.com --username techacc -p $TOKEN 2>/dev/null
        env:
          TOKEN: ${{ secrets.PERSONAL_DEV_TOKEN }}
      
      - name: Print the tag
        run: export APP_TAG=`printf $(git show-ref --abbrev=7 $GITHUB_REF)` && docker pull docker.pkg.github.com/syukur91/mono-repo/hello-github:$APP_TAG
        env:
          GITHUB_REF: ${{ toJson(github.ref) }}
        