name: ref-tag
on:
  push:
    tags:
      - mono-code-prod-*

jobs:
  miyazaki-infra-staging-deployment:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Check the cntext
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}